#! /bin/bash

if [ -n "$BASH_VERSION" ]; then
	# look for MacPorts bash completion
	if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
	    . /opt/local/etc/profile.d/bash_completion.sh
	fi

	if [ -f /opt/local/share/git-core/git-prompt.sh ]; then
	    . /opt/local/share/git-core/git-prompt.sh
	fi

	# look for homebrew bash completion
	if [ -f $(brew --prefix)/etc/bash_completion ]; then
	  . $(brew --prefix)/etc/bash_completion
	fi
fi