#! /bin/bash
# Requires Powerline patched fonts: https://gist.github.com/1595572
# Colors from http://www.arwin.net/tech/bash.php

case "$TERM" in
    xterm-color) color_prompt=yes;;
	xterm-256color) color_prompt=yes;;
esac

SEPARATOR="⮀"
SEPARATOL="⮂"
BRANCH="⭠"

# pass foreground then background (optional)
function _color() {
	local PROMPT_COLOR_OUTPUT="\[\e[0m\]"
	
	if ! [ -z $1 ]; then
		PROMPT_COLOR_OUTPUT="\[\e[$1m\]"
	fi

	if ! [ -z $2 ]; then
		PROMPT_COLOR_OUTPUT="\[\e[$2m\]${PROMPT_COLOR_OUTPUT}"
	fi
	
	echo $PROMPT_COLOR_OUTPUT
}

function _gitStatus() {	
	if ! [ `type -t __git_ps1`"" == 'function' ]; then
		return
	fi
	
	local FORBIDDEN="homebrew.git"
	local GIT_STATUS_TEXT="$(__git_ps1 "%s")"
	
	if [[ -n "$GIT_STATUS_TEXT" ]]; then
		local GIT_REPO=''
		local GIT_REMOTE=`git remote -v`		
		local SHOW_GIT=1

		if ! [ -z "$GIT_REMOTE" ]; then	
			GIT_REPO=$(basename `echo $GIT_REMOTE | grep origin | grep push | awk '{print $2;}'`)
			for REPO in $FORBIDDEN; do
				if [ $GIT_REPO = $REPO ]; then
					SHOW_GIT=0
				fi
			done
			GIT_REPO="$GIT_REPO "
		fi
		
		if [ $SHOW_GIT = 1 ]; then
			GIT_STATUS="$(_color "1;30" "42")${SEPARATOR}$(_color)$(_color "37" "42") ${GIT_REPO}${BRANCH} ${GIT_STATUS_TEXT}$(_color)$(_color "32")${SEPARATOR}$(_color)"
		fi
	fi
	
	echo $GIT_STATUS
}

function _svnStatus() {
	local SVN_STATUS_TEXT=''
	local REVISION=$(svn info 2>/dev/null | awk '/^Revision:/{print $2}')
	
	if ! [ -z "$REVISION" ]; then
		SVN_STATUS_TEXT="$(_color "1;30" "46")${SEPARATOR}$(_color)$(_color "30" "46") svn r:${REVISION}$(_color)$(_color "36")${SEPARATOR}$(_color)";
	fi
	
	echo "$SVN_STATUS_TEXT"
}

function _pythonVirtualenv() {
    local PYTHON_VIRTUALENV=""
    	
    if  [ -z "$VIRTUAL_ENV" ]; then
        PYTHON_VIRTUALENV="$(_color "37" "43")foo`basename \"$VIRTUAL_ENV\"` $(_color)$(_color "1;30" "43")${SEPARATOL}$(_color)"
    fi
	
	echo "$PYTHON_VIRTUALENV"
}

function _prompt() {
	if ! [[ $? -eq 0 ]]; then
		STATUS_COLOR="1;31"
	fi
	
	local STATUS_COLOR="1;32"

	local LOCAL_HOSTNAME=`scutil --get LocalHostName`
	local PYTHON_VIRTUALENV=$(_pythonVirtualenv)

	local GIT_STATUS=$(_gitStatus)
	local SVN_STATUS=$(_svnStatus)
		
	SCM_STATUS="$(_color "30")${SEPARATOR}$(_color)"
	if ! [ -z "$GIT_STATUS" ]; then
		SCM_STATUS="$GIT_STATUS"
	elif ! [ -z "$SVN_STATUS" ]; then
		SCM_STATUS="$SVN_STATUS"
	fi
			
	PROMPT="$(_color "40" "37")\u$(_color)${SCM_STATUS} \w $(_color "$STATUS_COLOR")\$$(_color) "
	PS1=${PYTHON_VIRTUALENV}${PROMPT}
}

if [ "$color_prompt" = yes ]; then
    PROMPT_COMMAND=_prompt
else
	PS1='\[\e[1;32m\]\u@\h \W:$(__git_ps1) \$\[\e[0m\] '
fi
unset color_prompt