#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD);
MSG=$(cat "$1")
MSGLEN=$(echo "$MSG" | sed -e '/^$/d' -e '/^#/d' | wc -m | tr -d ' ')

if [[ $MSGLEN > 0 ]] && [[ $BRANCH =~ [A-Z]+[A-Z0-9]+-[0-9]+ ]]; then
  ISSUE="[$(echo $BRANCH | grep -o '[A-Z][A-Z]*-[0-9][0-9]*')]";
  if [[ "$MSG" != *"$ISSUE"* ]]; then
    echo "$ISSUE $MSG" > "$1"
  fi
fi
