#!/bin/bash
protected_branch='master'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# ignore slingshot
if [[ `pwd` =~ 'slingshot/data' ]]; then
    exit 0; # OK 
fi

# Not master, go go go
if ! [ $protected_branch = $current_branch ]; then
    exit 0; # OK
fi

tput bold && tput setaf 1;
echo -n "You're about to push master, are you sure? [y|N]"
tput sgr0;

read -n 1 -r < /dev/tty;
echo;

# Confirmed, OK to go
if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
    exit 0; # OK
fi

# Not confirmed, error out
exit 1; # Fail