---
# System Setup
- name: Install Nvidia drivers
  ansible.builtin.command: ubuntu-drivers autoinstall
  changed_when: ""

- name: Remove xfce4-screensaver
  ansible.builtin.apt:
    name: xfce4-screensaver
    state: absent

- name: Install base packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - git
      - htop
      - light-locker
      - p7zip
      - samba
      - software-properties-common

- name: Set light-locker as default screen lock mechanism
  ansible.builtin.command: xfconf-query -c xfce4-session -p /general/LockCommand -s "light-locker-command -l"
  changed_when: ""
