local OPT_HOMEBREW="/opt/homebrew"
if [[ -s "$OPT_HOMEBREW"/bin/brew ]]; then
    eval "$($OPT_HOMEBREW/bin/brew shellenv)"
fi

if [[ -s "$HOMEBREW_PREFIX"/opt/asdf/libexec/asdf.sh ]]; then
  . "$HOMEBREW_PREFIX"/opt/asdf/libexec/asdf.sh
elif [[ -s "$HOME/.asdf/asdf.sh" ]]; then
  . "$HOME"/.asdf/asdf.sh
fi

if [[ -s "$HOME"/.zprezto/runcoms/zprofile ]]; then
  . "$HOME"/.zprezto/runcoms/zprofile
fi
