#
# Executes commands at the start of an interactive session.
#

# Init Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt no_share_history

export HOMEBREW_INSTALL_CLEANUP=1
export COMPOSER_DISABLE_XDEBUG_WARN=1
export GIT_PS1_SHOWDIRTYSTATE=true
export EDITOR="vim"

export PAGER="less"
export LESS="$LESS --no-init --quit-if-one-screen"

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

if [[ -d "$HOME"/Projects/dot-files/bin ]]; then
  PATH="$PATH:$HOME/Projects/dot-files/bin"
fi

if [[ -d "$HOME"/bin ]]; then
  PATH="$PATH:$HOME/bin"
fi

GEMDIR=$(gem environment gemdir)
if [[ -d "$GEMDIR"/bin ]]; then
  PATH="$GEMDIR/bin:$PATH"
fi
export PATH

# suffix aliases
alias -s {yaml,json,md,html,txt,csv,php,js,java,scala,py}="code"

if [[ $(which -s http) = 0 ]]; then
  alias http="http --style perldoc"
fi

alias ls="ls -GF"
alias vime="vim +'normal Go'"

alias diffc="git diff --color=never | code -"

# git clone https://github.com/athityakumar/colorls.git
# gem update colorls
if [[ $(which -s colorls) = 0 ]]; then
  alias l="colorls --light --sort-dirs"
  alias la="colorls --light --sort-dirs -lA"
  alias lt="colorls --light --tree"
fi

function flush-font-cache {
	sudo atsutil databases -remove
}

function md {
  pandoc -t html $1 | w3m -graph -T text/html
}

function tm {
  CC="";
  if [[ $TERM_PROGRAM == "iTerm"* ]]; then
    CC="-CC";
  fi
  
  tmux $CC new-session -s wookiee -c ~/Projects \; \
    split-window -h \; \
    select-pane -t 0 \; \
    split-window -v \; \
    select-pane -t 0 \;
}

function thermlog() {
    pmset -g thermlog
}

unalias mysql;

if [[ -f ~/.localrc ]]; then
  source ~/.localrc
fi
