#
# Executes commands at the start of an interactive session.
#

# Init Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v
setopt no_share_history

export HOMEBREW_INSTALL_CLEANUP=1
export COMPOSER_DISABLE_XDEBUG_WARN=1
export GIT_PS1_SHOWDIRTYSTATE=true
export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"
export LESS="$LESS --no-init --quit-if-one-screen"

if type brew &>/dev/null; then
  # init zsh completions on Mac 'cause they're from homebrew
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
  autoload -Uz compinit
  compinit
fi

if [[ -d "$HOME"/Projects/dot-files/bin ]]; then
  PATH="$PATH:$HOME/Projects/dot-files/bin"
fi

if [[ -d "$HOME"/bin ]]; then
  PATH="$PATH:$HOME/bin"
fi

GEMDIR=$(gem environment gemdir)
if [[ -d "$GEMDIR"/bin ]]; then
  PATH="$GEMDIR/bin:$PATH"
fi
export PATH

# suffix aliases
alias -s {yaml,json,md,html,txt,csv,php,js,java,scala,py}="code"

if type http &> /dev/null; then
  alias http="http --style perldoc"
fi

alias cal="ncal -b"
alias vime="vim +'normal Go'"

alias diffc="git diff --color=never | code -"

if type exa &> /dev/null; then
  alias ls="exa -F --git --time-style=long-iso"
else
  alias ls="ls -GF --time-style=long-iso"
fi

# git clone https://github.com/athityakumar/colorls.git
# gem update colorls
if [[ $(which -s colorls) = 0 ]]; then
  alias l="colorls --light --sort-dirs"
  alias la="colorls --light --sort-dirs -lA"
  alias lt="colorls --light --tree"
fi

function flush-font-cache {
	sudo atsutil databases -remove
}

function md {
  pandoc -t html $1 | w3m -graph -T text/html
}

function tm {
  CC="";
  if [[ $TERM_PROGRAM == "iTerm"* ]]; then
    CC="-CC";
  fi
  
  tmux $CC new-session -s wookiee -c ~/Projects \; \
    split-window -h \; \
    select-pane -t 0 \; \
    resize-pane -t 0 -x 30% \; \
	split-window -v \; \
    select-pane -t 0 \;
}

unalias mysql;
#autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
#add-zsh-hook chpwd chpwd_recent_dirs

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert always

if [[ -s "$HOMEBREW_PREFIX"/opt/asdf/libexec/asdf.sh ]]; then
  . "$HOMEBREW_PREFIX"/opt/asdf/libexec/asdf.sh
elif [[ -s "$HOME/.asdf/asdf.sh" ]]; then
  . "$HOME"/.asdf/asdf.sh
fi

if [[ -f ~/.localrc ]]; then
  source ~/.localrc
fi
