- hosts: localhost
  become: true
  vars_files:
    - vars/default.yaml
  tasks:
    - name: Install Nvidia drivers
      shell: ubuntu-drivers autoinstall
    - name: Install base packages
      apt: name={{item}} state=latest update_cache=yes
      loop:
        - apt-transport-https
        - ca-certificates
        - git
        - htop
        - p7zip
        - samba
        - software-properties-common
    - name: Install packages for site authoring
      apt: name={{item}} state=latest update_cache=yes
      loop:
        - libgsl-dev
    # Docker
    - name: Add Docker apt GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository: deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      state: present
    - name: Install Docker
      apt: update_cache=yes state=latest name={{item}}
      loop:
        - docker-ce
        - docker-ce-cli
        - docker-compose
    - name: Move Docker container root
      template:
        src: docker-daemon.json
        dest: /etc/docker/
      notify: restart docker
    - name: Start containers
      shell: cd /mnt/containers/docker && make up
    - name: Image Editing tools
      apt: name={{item}} state=latest update_cache=yes
      loop:
        - gimp
        - hugin
        - hugin-tools